import Navbar from "@/components/navbar";
import { AuthProvider } from "@/providers/auth-provider";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<AuthProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<div
						id="rootLayout"
						className="py-4 px-16 flex flex-col min-h-screen "
					>
						<Navbar />
						<main className="overflow-hidden flex-1">{children}</main>
					</div>
				</body>
			</html>
		</AuthProvider>
	);
}
